version: '3.8'

services:
  postgres_db:
    image: postgis/postgis:15-3.3
    container_name: seattle_info_postgres_prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - seattle_info_net_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seattle_info_app_prod
    ports:
      - "80:${SERVER_PORT:-8080}"
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - /home/ubuntu/seatle_info/config/firebase-key.json:/app/secret/firebase-key.json:ro
    networks:
      - seattle_info_net_prod

volumes:
  postgres_data_prod:

networks:
  seattle_info_net_prod:
    driver: bridge
