// File: cmd/server/main.go
package main

import (
	"context"
	"log" // Standard log for critical startup/shutdown messages before/after zap is active
	"os"
	"os/signal"
	"syscall"

	"seattle_info_backend/internal/config"
	platformElasticsearch "seattle_info_backend/internal/platform/elasticsearch" // Re-add
	"go.uber.org/zap"                                                            // Re-add
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("FATAL: Failed to load configuration: %v", err)
	}

	// initializeServer is generated by Wire and is in wire_gen.go.
	// It now sets up everything: DB, logger, services, handlers, jobs, and the server itself.
	// Signature changed to 3 return values; ESClient and AppLogger are in server struct.
	server, cleanup, err := initializeServer(cfg)
	if err != nil {
		// Use standard log here as appLogger might not be initialized if error occurs early in initializeServer
		log.Fatalf("FATAL: Failed to initialize server: %v", err)
	}
	// Defer the cleanup function from Wire, which handles DB closing, logger syncing.
	// Server.Shutdown (called below) handles job stopping.
	defer cleanup()

	// Create Elasticsearch index if it doesn't exist
	// Access ESClient and AppLogger from the server object.
	if server.ESClient != nil {
		// Ensure AppLogger is also not nil, though it should be set if server init was successful.
		if server.AppLogger == nil {
			log.Println("WARN: AppLogger is nil on server object, cannot create ES index. This is unexpected.")
		} else {
			if err := platformElasticsearch.CreateListingsIndexIfNotExists(server.ESClient, server.AppLogger); err != nil {
				server.AppLogger.Error("Failed to create Elasticsearch listings index. Depending on app logic, this might be fatal.", zap.Error(err))
				// For now, log and continue. If ES is critical:
				// log.Fatalf("FATAL: Failed to create Elasticsearch index: %v", err)
			}
		}
	} else {
		// Log this case using standard log if AppLogger might be nil, or use AppLogger if available.
		// If server.AppLogger is guaranteed to be non-nil here, prefer it.
		if server.AppLogger != nil {
			server.AppLogger.Info("Elasticsearch client (server.ESClient) not initialized, skipping index creation.")
		} else {
			log.Println("INFO: Elasticsearch client (server.ESClient) not initialized, skipping index creation.")
		}
	}

	// Start the server in a new goroutine. Server.Start() also starts jobs.
	go func() {
		if err := server.Start(); err != nil && err.Error() != "http: Server closed" {
			log.Fatalf("FATAL: Server failed to start or crashed: %v", err)
		}
	}()

	// Wait for an interrupt signal to gracefully shut down the server.
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	sig := <-quit
	log.Printf("INFO: Received signal '%s'. Shutting down server...", sig)

	// Create a context with a timeout for the shutdown.
	shutdownCtx, cancelShutdown := context.WithTimeout(context.Background(), cfg.ServerTimeout)
	defer cancelShutdown()

	// Attempt to gracefully shut down the server (which includes stopping jobs).
	if err := server.Shutdown(shutdownCtx); err != nil {
		log.Printf("ERROR: Server forced to shutdown due to error: %v", err)
	} else {
		log.Println("INFO: Server shutdown complete.")
	}

	log.Println("INFO: Application exiting.")
}
