name: Build and Deploy to EC2 via GHCR

on:
  push:
    branches:
      - main # Or your default branch

env:
  # Replace with your GitHub username and repository name
  # e.g., ghcr.io/nahoma123/seatle_info
  IMAGE_NAME: ghcr.io/nahoma123/seatle_info
  # SERVER_HOST is now defined here for global use if needed,
  # but also explicitly in steps for clarity where used directly by scripts.
  SERVER_HOST_GLOBAL: ${{ secrets.SERVER_HOST }} # Using a different name to avoid conflict if a step redefines

jobs:
  build-and-push-image:
    name: Build Docker image and push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Your GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha # Will create a tag like ghcr.io/user/repo:commit-sha
            type=raw,value=latest,enable={{is_default_branch}} # Tag 'latest' for default branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-ec2:
    name: Deploy to EC2 instance
    runs-on: ubuntu-latest
    needs: build-and-push-image # Run only after the image is built and pushed

    steps:
      - name: Set up SSH key and known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          # Explicitly making SERVER_HOST available to this script
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

      - name: Copy Firebase key to server (if needed at runtime)
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }} # Explicitly making SERVER_HOST available
          SERVER_USER: ${{ secrets.SERVER_USER }}
          FIREBASE_ADMIN_SDK_JSON_CONTENT: ${{ secrets.FIREBASE_ADMIN_SDK_JSON }}
          FIREBASE_KEY_PATH_ON_SERVER: ${{ secrets.FIREBASE_KEY_PATH_ON_SERVER }}
        run: |
          echo "$FIREBASE_ADMIN_SDK_JSON_CONTENT" > ./firebase-key-to-copy.json
          scp -i ~/.ssh/id_rsa ./firebase-key-to-copy.json ${SERVER_USER}@${SERVER_HOST}:${FIREBASE_KEY_PATH_ON_SERVER}
          rm ./firebase-key-to-copy.json # Clean up

      - name: SSH, Migrate, Deploy on Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }} # Explicitly making SERVER_HOST available
          SERVER_USER: ${{ secrets.SERVER_USER }}
          GHCR_IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GHCR_USER: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ssh -i ~/.ssh/id_rsa ${SERVER_USER}@${SERVER_HOST} << EOF
            set -e # Exit immediately if a command exits with a non-zero status.

            cd ~/seatle_info  # Or your project directory on the server

            echo "Logging into GHCR..."
            echo "${GHCR_TOKEN}" | sudo docker login ghcr.io -u "${GHCR_USER}" --password-stdin

            echo "Pulling latest image from GHCR..."
            sudo docker pull ${GHCR_IMAGE_NAME}:latest

            echo "Running database migrations..."
            # Ensure your docker-compose.yml on the server has a 'migrate' service
            # and DB_SOURCE is available in its environment (e.g., from .env file)
            sudo docker-compose -f docker-compose.yml run --rm migrate migrate -path /migrations -database "\$DB_SOURCE" up
            # Note: Escaped $DB_SOURCE as "\$DB_SOURCE" because the heredoc is single-quoted for the outer EOF.
            # This means variable expansion for $DB_SOURCE should happen on the server side.
            # If DB_SOURCE itself needs to be passed from GitHub Secrets (not recommended for DB credentials),
            # the heredoc quoting and variable passing would need to be different.

            echo "Starting services with docker-compose..."
            sudo docker-compose -f docker-compose.yml up -d

            echo "Pruning old Docker images..."
            sudo docker image prune -af
          EOF
